version: "1"

services:
  colmap-glomap:
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 7800:7800
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
        - ./data:/data

    command: [ "/bin/bash", "-c", "--", "while true; do sleep 30; done;" ]